package com.bozo.greendaolearn.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bozo.greendaolearn.entities.MaterialEntity;

import com.bozo.greendaolearn.greendao.MaterialEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig materialEntityDaoConfig;

    private final MaterialEntityDao materialEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        materialEntityDaoConfig = daoConfigMap.get(MaterialEntityDao.class).clone();
        materialEntityDaoConfig.initIdentityScope(type);

        materialEntityDao = new MaterialEntityDao(materialEntityDaoConfig, this);

        registerDao(MaterialEntity.class, materialEntityDao);
    }
    
    public void clear() {
        materialEntityDaoConfig.clearIdentityScope();
    }

    public MaterialEntityDao getMaterialEntityDao() {
        return materialEntityDao;
    }

}
