package com.bozo.greendaolearn.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bozo.greendaolearn.entities.MaterialEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "material".
*/
public class MaterialEntityDao extends AbstractDao<MaterialEntity, Long> {

    public static final String TABLENAME = "material";

    /**
     * Properties of entity MaterialEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Price = new Property(2, double.class, "price", false, "price");
        public final static Property Number = new Property(3, int.class, "number", false, "number");
        public final static Property Store = new Property(4, String.class, "store", false, "store");
    }


    public MaterialEntityDao(DaoConfig config) {
        super(config);
    }
    
    public MaterialEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"material\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"name\" TEXT," + // 1: name
                "\"price\" REAL NOT NULL ," + // 2: price
                "\"number\" INTEGER NOT NULL ," + // 3: number
                "\"store\" TEXT);"); // 4: store
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"material\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MaterialEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindDouble(3, entity.getPrice());
        stmt.bindLong(4, entity.getNumber());
 
        String store = entity.getStore();
        if (store != null) {
            stmt.bindString(5, store);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MaterialEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindDouble(3, entity.getPrice());
        stmt.bindLong(4, entity.getNumber());
 
        String store = entity.getStore();
        if (store != null) {
            stmt.bindString(5, store);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MaterialEntity readEntity(Cursor cursor, int offset) {
        MaterialEntity entity = new MaterialEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getDouble(offset + 2), // price
            cursor.getInt(offset + 3), // number
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // store
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MaterialEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrice(cursor.getDouble(offset + 2));
        entity.setNumber(cursor.getInt(offset + 3));
        entity.setStore(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MaterialEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MaterialEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MaterialEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
